### ISSUE TITLE
nodejs

### ISSUE THREAD

**Issue by james2702** [gekkedev/youlikehitsbot#1]
how to use your code in node js or npm
thanks

**Comment by gekkedev** [comment]
The code is too far from being automated enough yet to use it with Node.JS Although it definitely is an interesting idea for future development. You'd have to:
- replace jQuery with a different lib or pure JS (difficult because the selectors used are slightly 
sophisticated)
- port it over from Tamper-/Greasemonkey's way of handling websites (replace the sandboxing API)
- set up at a CLI
- session handling
and some unexpected trouble you might run into. This script is currently more a helper than a fully automated point harvester. The features it supports should allow you to comply with their expectations (e.g. actually watching videos) which is something you won't do when using Node.JS.
Another solution could be to make a two-way executable script.
